#!/usr/bin/python3
""" State class Module"""

from sqlalchemy import Column, Integer, String, MetaData
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
# mymetadata = MetaData()


class State(Base):
    """ Defines State class

    Attributes:
        __tablename__ : links to states table
        id: Represents a column of an autogenerated, unique integer
            and cannit be null and is a primary key
        name: Represents a column of a string with 128 max characters
              and can't be null
    """
    __tablename__ = 'states'
    id = Column(Integer, nullable=False, unique=True, primary_key=True)
    name = Column(String(128), nullable=False)
